name: Sync File from URL

on:
  # 定时触发
  schedule:
    - cron: '0 * * * *'  # 每小时的整点运行
  # 手动触发
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Download file from URL
      run: |
        curl -o jd.txt https://raw.githubusercontent.com/WeiGiegie/vpm/main/lq.snippet

    - name: Commit and push changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add jd.txt
        git commit -m "Sync jd.txt from WeiGiegie/vpm repository"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
